### ISSUE TITLE
Error: expected expression, found keyword `mut`

### ISSUE THREAD

**Issue by ghost** [programatik29/axum-debug#2]
error: expected expression, found keyword `mut`
  --> server/src/handler/users.rs:12:19
   |
12 |     ValidatedJson(mut input): ValidatedJson<InitInput>,
   |                   ^^^ expected expression

**Comment by programatik29** [comment]
Can you send the code? Also does your program compile without using `debug_handler`?

**Comment by programatik29** [comment]
This crate is moved to [axum] repository.

This [pull request](https://github.com/tokio-rs/axum/pull/518) is solves this problem.

[axum]: https://github.com/tokio-rs/axum
